version: '3.4'
 
networks:
  double-v-partners-dev:
    driver: bridge 

services:
  mydockerapi:
    image: double-v-partners:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=double_v_partners;username=doubleVP;password=doubleVP"
    networks:
      - double-v-partners-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./Database/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "doubleVP"
      POSTGRES_PASSWORD: "doubleVP"
      POSTGRES_DB: "double_v_partners"
    networks:
      - double-v-partners-dev
volumes:
  db_volume: